### PR TITLE
fix: added tools hover interaction icon component

### LINKED ISSUE #318: Tools hover interaction
### Description
Create the component as shown in the video attached below.

### Animation Preview
- Screenshot/Video:

https://github.com/user-attachments/assets/dc5db263-35db-414f-a6e1-5dfcbca3b5cb

> [!NOTE]  
> Please refer to the **Animata contributing guidelines** available [here](https://www.animata.design/docs/contributing) for rules on how to contribute to the project. Let us know in the comments if you’re working on this issue, and feel free to ask any questions!

### Requirements
1. Create a new animated component that matches the provided design.
2. Add example usage of the component in the documentation or storybook.

<details>
  <summary>
    <h3> Guidelines & Best Practices</h3>
  </summary>

- Write reusable and clean code following the project’s style guide.
- The component should be **fully customizable**. The user should be able to modify props such as duration, easing, color, and size where applicable.
- Follow the [Contributing Guidelines](https://www.animata.design/docs/contributing) before submitting your pull request.

</details>

> [!IMPORTANT]  
> To ensure more contributors have the opportunity to participate, we kindly request that:
> - Each contributor submits only **one pull request** related to this issue.
> - If you're interested in working on this issue, please comment below. We will assign the issue on a **first-come, first-served basis**.

---

### Additional Resources
Posted on X by: https://x.com/itsonly_anoop/status/1839339901751525425

---

> [!Tip]
> Join our Discord community if you need help or have any questions. We're here to help you get started and guide you through the process. [Join now](https://discord.gg/YfvqMf5MTE)

### PR DESCRIPTION
**Pull request by bandhan-majumder**
fixes #318 

previews:
1. https://www.loom.com/share/2d1e22cbb932456c83aa9e495db6830b
2. https://www.loom.com/share/d345defdccf34fceb9c0c7d4e0ecac7f?sid=f5e53388-4144-4765-b7a7-fa07352f5322

description:
Added tools hover interaction using radix-ui react icons and framer motion. Default imports are Twitter/x, Framer, Figma, Instagram, GitHub, LinkedIn, and it shows Square-Box icon if related icon is not found. User can add their needed icons and steps are given in the `hover-interaction.mdx`

### CODE REVIEW

File: animata/icon/hover-interaction.tsx [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+    case "linkedin":
+      return LinkedInLogoIcon;
+    case "github":
+      return GitHubLogoIcon;
+    case "figma":
+      return FigmaLogoIcon;
+    default:
+      return SquareIcon;
+  }
+};
```
Comment (hari) [inline animata/icon/hover-interaction.tsx:57]: You can use map here.

**Review by hari — APPROVED** [review]

File: animata/icon/hover-interaction.tsx (hunk 1 above)
Comment (bandhan-majumder) [reply animata/icon/hover-interaction.tsx]: done
